-- ============================================================
-- COLORIDO 2K26 — Seed data for content tables
-- Generated from the original data/*.js files so the site has
-- real content immediately after the schema migrations run.
-- Safe to re-run: each block clears its table first.
-- ============================================================

-- ── events ──────────────────────────────────────────────────
delete from events;

insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('fine-arts', 'Fine Arts', 'Cultural', 'Open', 'palette', 'Express imagination through art and creativity.', 'A celebration of visual creativity where artists bring blank canvases to life. Participants showcase their skills across painting, sketching, and mixed media in a live competition setting.', 'Art Block, Room 101', '15 OCT 2026', '10:00 AM', 'Individual', '₹150', '["Participants must bring their own art materials.","Time limit: 3 hours per round.","Themes will be announced on the spot.","Judges decision will be final."]'::jsonb, '[{"time":"10:00 AM","activity":"Reporting & Material Setup"},{"time":"10:30 AM","activity":"Round 1 — Live Painting"},{"time":"01:00 PM","activity":"Lunch Break"},{"time":"02:00 PM","activity":"Round 2 — Sketching"},{"time":"04:00 PM","activity":"Results Announcement"}]'::jsonb, 0);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('music-solo', 'Music — Solo', 'Cultural', 'Music & Band', 'mic', 'A single voice. A single instrument. Pure magic.', 'Solo performers take the stage to showcase their vocal or instrumental talent. From classical ragas to contemporary hits, this is where individual brilliance shines.', 'Main Auditorium', '15 OCT 2026', '11:00 AM', 'Individual', '₹200', '["Time limit: 5 minutes per performance.","Backing tracks allowed; no lip-syncing.","Participants must bring their own instruments.","Original compositions are encouraged."]'::jsonb, '[{"time":"11:00 AM","activity":"Reporting & Sound Check"},{"time":"11:30 AM","activity":"Performance Round 1"},{"time":"01:00 PM","activity":"Lunch Break"},{"time":"02:00 PM","activity":"Final Round"},{"time":"04:00 PM","activity":"Results"}]'::jsonb, 1);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('music-group', 'Music — Group', 'Cultural', 'Music & Band', 'music', 'When voices and instruments unite, the stage comes alive.', 'Bands and musical groups perform together, blending vocals, guitars, drums, and more. A high-energy showcase of collaborative musical talent.', 'Main Auditorium', '16 OCT 2026', '10:00 AM', '3–8 Members', '₹800', '["Time limit: 8 minutes per performance.","Each group must have a minimum of 3 members.","Own instruments required; sound system provided.","No pre-recorded vocals allowed."]'::jsonb, '[{"time":"10:00 AM","activity":"Reporting & Setup"},{"time":"10:30 AM","activity":"Preliminary Round"},{"time":"01:00 PM","activity":"Lunch Break"},{"time":"02:00 PM","activity":"Final Round"},{"time":"05:00 PM","activity":"Results"}]'::jsonb, 2);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('dance-solo', 'Dance — Solo', 'Cultural', 'Dance', 'zap', 'One dancer. One stage. Infinite expression.', 'Solo dancers light up the stage with performances spanning classical, hip-hop, contemporary, and freestyle styles. A true test of individual artistry and stage presence.', 'Open-Air Stage', '16 OCT 2026', '11:00 AM', 'Individual', '₹200', '["Time limit: 5 minutes per performance.","Props allowed; fire/hazardous props prohibited.","Track must be submitted 1 hour before performance.","Costumes must be appropriate for a college event."]'::jsonb, '[{"time":"11:00 AM","activity":"Reporting"},{"time":"11:30 AM","activity":"Preliminary Round"},{"time":"01:00 PM","activity":"Lunch Break"},{"time":"02:30 PM","activity":"Final Round"},{"time":"04:30 PM","activity":"Results"}]'::jsonb, 3);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('dance-group', 'Dance — Group', 'Cultural', 'Dance', 'users', 'Synchronicity, energy, and collective rhythm.', 'Dance crews bring their best choreography to the stage. From cinematic themes to cultural fusion, group dance is one of the most anticipated events of COLORIDO.', 'Open-Air Stage', '17 OCT 2026', '10:00 AM', '4–12 Members', '₹1,000', '["Time limit: 8 minutes per performance.","Minimum 4 members per group.","Track must be submitted 2 hours before performance.","No hazardous props; safety is the priority."]'::jsonb, '[{"time":"10:00 AM","activity":"Reporting"},{"time":"10:30 AM","activity":"Preliminary Round"},{"time":"01:00 PM","activity":"Lunch Break"},{"time":"02:00 PM","activity":"Final Round"},{"time":"05:00 PM","activity":"Results"}]'::jsonb, 4);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('choreoday', 'Choreoday', 'Cultural', 'Theme Based', 'sparkles', 'A theme-based choreography championship.', 'Choreoday is a theme-based dance competition where teams build an entire performance around a central narrative. Storytelling through movement, music, and visual design.', 'Main Auditorium', '17 OCT 2026', '02:00 PM', '6–15 Members', '₹1,200', '["Theme will be announced 1 week before the event.","Time limit: 10 minutes per performance.","Minimum 6 members per team.","Props and costumes must align with the theme."]'::jsonb, '[{"time":"02:00 PM","activity":"Reporting"},{"time":"02:30 PM","activity":"Performance Round"},{"time":"05:30 PM","activity":"Results"}]'::jsonb, 5);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('dramatics', 'Dramatics', 'Cultural', 'Open', 'drama', 'Where stories come alive on stage.', 'A stage play competition where teams enact short plays, skits, or mime performances. Original scripts, powerful acting, and creative direction take center stage.', 'Seminar Hall', '16 OCT 2026', '02:00 PM', '4–10 Members', '₹600', '["Time limit: 15 minutes per performance.","Original scripts are encouraged.","Minimal props; focus on acting and direction.","Language: English, Telugu, or Hindi."]'::jsonb, '[{"time":"02:00 PM","activity":"Reporting"},{"time":"02:30 PM","activity":"Performance Round"},{"time":"05:30 PM","activity":"Results"}]'::jsonb, 6);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('fashion-show', 'Fashion Show', 'Cultural', 'Open', 'crown', 'Glamour, style, and attitude on the runway.', 'A dazzling runway competition where teams showcase themed fashion sequences. Creativity in design, confidence in walk, and overall presentation are judged.', 'Open-Air Stage', '17 OCT 2026', '04:00 PM', '6–12 Members', '₹1,000', '["Each team gets 8 minutes on the runway.","Themes: Traditional, Indo-Western, and Creative.","No offensive or inappropriate costumes.","Judges will evaluate design, walk, and presentation."]'::jsonb, '[{"time":"04:00 PM","activity":"Reporting & Backstage Setup"},{"time":"04:30 PM","activity":"Round 1 — Traditional"},{"time":"05:30 PM","activity":"Round 2 — Creative"},{"time":"06:30 PM","activity":"Results"}]'::jsonb, 7);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('tekraft-events', 'Tekraft Events', 'Cultural', 'Open', 'cpu', 'Where technology meets creativity.', 'A series of tech-creative events including coding challenges, UI/UX design contests, and tech quiz competitions. For the innovators and problem-solvers.', 'Computer Lab, Block C', '15 OCT 2026', '10:00 AM', 'Individual / Team of 2', '₹250', '["Coding round: 90 minutes, 3 problems.","UI/UX round: 2 hours, theme-based design.","Tech quiz: 30 questions, 30 minutes.","Internet access is restricted during coding."]'::jsonb, '[{"time":"10:00 AM","activity":"Reporting"},{"time":"10:30 AM","activity":"Coding Challenge"},{"time":"12:00 PM","activity":"Tech Quiz"},{"time":"01:00 PM","activity":"Lunch Break"},{"time":"02:00 PM","activity":"UI/UX Design Round"},{"time":"04:00 PM","activity":"Results"}]'::jsonb, 8);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('literary', 'Literary', 'Cultural', 'Open', 'book-open', 'Words that inspire, stories that move.', 'A literary competition featuring debate, creative writing, poetry recitation, and quiz events. For those who wield words with precision and passion.', 'Library Seminar Room', '16 OCT 2026', '10:00 AM', 'Individual', '₹150', '["Debate: 4 minutes per speaker.","Creative writing: 45 minutes, on-the-spot topic.","Poetry: original or published, 3 minutes.","Quiz: teams of 2, 30 questions."]'::jsonb, '[{"time":"10:00 AM","activity":"Reporting"},{"time":"10:30 AM","activity":"Debate Competition"},{"time":"12:00 PM","activity":"Creative Writing"},{"time":"01:00 PM","activity":"Lunch Break"},{"time":"02:00 PM","activity":"Poetry Recitation"},{"time":"03:00 PM","activity":"Literary Quiz"},{"time":"04:30 PM","activity":"Results"}]'::jsonb, 9);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('basketball-boys', 'Basketball', 'Sports', 'Boys', 'basketball', 'Fast breaks, sharp shooting, and team glory.', 'A high-intensity basketball tournament for boys. Teams battle through knockout rounds to claim the championship trophy.', 'College Sports Ground', '15 OCT 2026', '10:00 AM', '5 + Substitutes', '₹500', '["Each team must report 30 minutes before match time.","Matches follow standard FIBA rules.","Knockout format; single elimination.","Decisions of officials will be final."]'::jsonb, '[{"time":"10:00 AM","activity":"Team Reporting"},{"time":"10:30 AM","activity":"Match 1"},{"time":"12:00 PM","activity":"Match 2"},{"time":"02:00 PM","activity":"Semifinals"},{"time":"04:00 PM","activity":"Final"}]'::jsonb, 10);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('volleyball-boys', 'Volleyball', 'Sports', 'Boys', 'circle', 'Spikes, blocks, and relentless rallies.', 'A competitive volleyball tournament for boys. Teams compete in a knockout format, with each match testing skill, coordination, and endurance.', 'College Sports Ground', '16 OCT 2026', '10:00 AM', '6 + Substitutes', '₹500', '["Each team must report 30 minutes before match time.","Matches follow standard FIVB rules.","Best of 3 sets per match.","Decisions of officials will be final."]'::jsonb, '[{"time":"10:00 AM","activity":"Team Reporting"},{"time":"10:30 AM","activity":"Match 1"},{"time":"12:00 PM","activity":"Match 2"},{"time":"02:00 PM","activity":"Semifinals"},{"time":"04:00 PM","activity":"Final"}]'::jsonb, 11);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('table-tennis-boys', 'Table Tennis', 'Sports', 'Boys', 'circle-dot', 'Precision, speed, and razor-sharp reflexes.', 'An individual and team table tennis competition for boys. Fast-paced matches in a knockout format for singles and doubles.', 'Indoor Sports Hall', '17 OCT 2026', '10:00 AM', 'Individual / Team of 2', '₹200', '["Best of 5 games per match.","Standard ITTF rules apply.","Players must bring their own paddles.","Decisions of officials will be final."]'::jsonb, '[{"time":"10:00 AM","activity":"Reporting"},{"time":"10:30 AM","activity":"Preliminary Round"},{"time":"12:00 PM","activity":"Quarterfinals"},{"time":"02:00 PM","activity":"Semifinals"},{"time":"04:00 PM","activity":"Final"}]'::jsonb, 12);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('throwball-girls', 'Throwball', 'Sports', 'Girls', 'target', 'Power, placement, and team spirit.', 'A dynamic throwball tournament for girls. Teams compete with energy and coordination in a knockout format.', 'College Sports Ground', '15 OCT 2026', '10:00 AM', '7 + Substitutes', '₹500', '["Each team must report 30 minutes before match time.","Standard throwball rules apply.","Best of 3 sets per match.","Decisions of officials will be final."]'::jsonb, '[{"time":"10:00 AM","activity":"Team Reporting"},{"time":"10:30 AM","activity":"Match 1"},{"time":"12:00 PM","activity":"Match 2"},{"time":"02:00 PM","activity":"Semifinals"},{"time":"04:00 PM","activity":"Final"}]'::jsonb, 13);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('tennikoit-girls', 'TenniKoit', 'Sports', 'Girls', 'circle-dot', 'Agility, focus, and quick reflexes.', 'A fast-paced tennikoit (ring tennis) competition for girls. Individual and team events in a knockout format.', 'Indoor Sports Hall', '16 OCT 2026', '10:00 AM', 'Individual / Team of 2', '₹200', '["Best of 3 games per match.","Standard tennikoit rules apply.","Players must bring their own koit rings.","Decisions of officials will be final."]'::jsonb, '[{"time":"10:00 AM","activity":"Reporting"},{"time":"10:30 AM","activity":"Preliminary Round"},{"time":"12:00 PM","activity":"Quarterfinals"},{"time":"02:00 PM","activity":"Semifinals"},{"time":"04:00 PM","activity":"Final"}]'::jsonb, 14);
insert into events (id, name, category, division, icon, tagline, description, venue, event_date, event_time, team_size, fee, rules, schedule, sort_order) values ('table-tennis-girls', 'Table Tennis', 'Sports', 'Girls', 'circle-dot', 'Precision, speed, and razor-sharp reflexes.', 'An individual and team table tennis competition for girls. Fast-paced matches in a knockout format for singles and doubles.', 'Indoor Sports Hall', '17 OCT 2026', '10:00 AM', 'Individual / Team of 2', '₹200', '["Best of 5 games per match.","Standard ITTF rules apply.","Players must bring their own paddles.","Decisions of officials will be final."]'::jsonb, '[{"time":"10:00 AM","activity":"Reporting"},{"time":"10:30 AM","activity":"Preliminary Round"},{"time":"12:00 PM","activity":"Quarterfinals"},{"time":"02:00 PM","activity":"Semifinals"},{"time":"04:00 PM","activity":"Final"}]'::jsonb, 15);

-- ── schedule_days ───────────────────────────────────────────
delete from schedule_items;
delete from schedule_days;

insert into schedule_days (id, label, event_date, sort_order) values ('day1', 'Day 01', '15 OCT 2026', 0);
insert into schedule_days (id, label, event_date, sort_order) values ('day2', 'Day 02', '16 OCT 2026', 1);
insert into schedule_days (id, label, event_date, sort_order) values ('day3', 'Day 03', '17 OCT 2026', 2);

-- ── schedule_items ──────────────────────────────────────────
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day1', '08:30 AM', 'Registration & Check-in', 'Main Gate', 0);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day1', '09:00 AM', 'Opening Ceremony', 'Main Auditorium', 1);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day1', '10:00 AM', 'Fine Arts Competition', 'Art Block', 2);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day1', '10:00 AM', 'Basketball (Boys)', 'Sports Ground', 3);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day1', '10:00 AM', 'Tekraft Events', 'Computer Lab', 4);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day1', '10:00 AM', 'Throwball (Girls)', 'Sports Ground', 5);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day1', '11:00 AM', 'Music — Solo', 'Main Auditorium', 6);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day1', '01:00 PM', 'Lunch Break', 'Cafeteria', 7);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day1', '02:00 PM', 'Dramatics', 'Seminar Hall', 8);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day1', '04:00 PM', 'Results — Day 1 Events', 'Main Auditorium', 9);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day2', '09:00 AM', 'Reporting & Warm-up', 'Sports Ground', 0);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day2', '10:00 AM', 'Music — Group', 'Main Auditorium', 1);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day2', '10:00 AM', 'Volleyball (Boys)', 'Sports Ground', 2);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day2', '10:00 AM', 'Literary Events', 'Library Seminar Room', 3);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day2', '10:00 AM', 'TenniKoit (Girls)', 'Indoor Sports Hall', 4);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day2', '11:00 AM', 'Dance — Solo', 'Open-Air Stage', 5);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day2', '01:00 PM', 'Lunch Break', 'Cafeteria', 6);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day2', '02:00 PM', 'Dramatics Finals', 'Seminar Hall', 7);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day2', '04:00 PM', 'Cultural Night', 'Open-Air Stage', 8);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day3', '09:00 AM', 'Reporting & Warm-up', 'Sports Ground', 0);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day3', '10:00 AM', 'Dance — Group', 'Open-Air Stage', 1);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day3', '10:00 AM', 'Table Tennis (Boys)', 'Indoor Sports Hall', 2);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day3', '10:00 AM', 'Table Tennis (Girls)', 'Indoor Sports Hall', 3);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day3', '02:00 PM', 'Choreoday', 'Main Auditorium', 4);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day3', '04:00 PM', 'Fashion Show', 'Open-Air Stage', 5);
insert into schedule_items (day_id, time, activity, venue, sort_order) values ('day3', '06:00 PM', 'Closing Ceremony & Prize Distribution', 'Main Auditorium', 6);

-- ── announcements ───────────────────────────────────────────
delete from announcements;

insert into announcements (title, announced_date, description, badge, sort_order) values ('Registration Opens', '25 September 2026', 'Registration for COLORIDO 2K26 is now open. Register early to secure your spot in your favorite events.', 'New', 0);
insert into announcements (title, announced_date, description, badge, sort_order) values ('Event Schedule Released', '27 September 2026', 'The full 3-day event schedule is now available on the Schedule page. Plan your COLORIDO experience.', 'Info', 1);
insert into announcements (title, announced_date, description, badge, sort_order) values ('Last Date for Registration', '05 October 2026', 'All registrations must be submitted by 5 October 2026, 11:59 PM. No extensions will be granted.', 'Urgent', 2);
insert into announcements (title, announced_date, description, badge, sort_order) values ('Choreoday Theme Announced', '10 October 2026', 'The theme for Choreoday 2K26 is "Roots & Wings" — celebrating where we come from and where we are going.', 'New', 3);
insert into announcements (title, announced_date, description, badge, sort_order) values ('Accommodation Details', '12 October 2026', 'Outstation participants can avail hostel accommodation. Contact the helpdesk for booking details.', 'Info', 4);

-- ── results ─────────────────────────────────────────────────
delete from results;

insert into results (category, event_name, winner, runner_up, sort_order) values ('cultural', 'Fine Arts', 'ABC College, Vijayawada', 'XYZ College, Guntur', 0);
insert into results (category, event_name, winner, runner_up, sort_order) values ('cultural', 'Music — Solo', 'PQR College, Hyderabad', 'LMN College, Visakhapatnam', 1);
insert into results (category, event_name, winner, runner_up, sort_order) values ('cultural', 'Music — Group', 'DEF College, Chennai', 'ABC College, Vijayawada', 2);
insert into results (category, event_name, winner, runner_up, sort_order) values ('cultural', 'Dance — Solo', 'GHI College, Bangalore', 'PQR College, Hyderabad', 3);
insert into results (category, event_name, winner, runner_up, sort_order) values ('cultural', 'Dance — Group', 'JKL College, Guntur', 'DEF College, Chennai', 4);
insert into results (category, event_name, winner, runner_up, sort_order) values ('cultural', 'Choreoday', 'MNO College, Tirupati', 'GHI College, Bangalore', 5);
insert into results (category, event_name, winner, runner_up, sort_order) values ('cultural', 'Dramatics', 'PQR College, Hyderabad', 'ABC College, Vijayawada', 6);
insert into results (category, event_name, winner, runner_up, sort_order) values ('cultural', 'Fashion Show', 'DEF College, Chennai', 'JKL College, Guntur', 7);
insert into results (category, event_name, winner, runner_up, sort_order) values ('sports', 'Basketball (Boys)', 'ABC College, Vijayawada', 'XYZ College, Guntur', 0);
insert into results (category, event_name, winner, runner_up, sort_order) values ('sports', 'Volleyball (Boys)', 'PQR College, Hyderabad', 'LMN College, Visakhapatnam', 1);
insert into results (category, event_name, winner, runner_up, sort_order) values ('sports', 'Table Tennis (Boys)', 'GHI College, Bangalore', 'MNO College, Tirupati', 2);
insert into results (category, event_name, winner, runner_up, sort_order) values ('sports', 'Throwball (Girls)', 'DEF College, Chennai', 'JKL College, Guntur', 3);
insert into results (category, event_name, winner, runner_up, sort_order) values ('sports', 'TenniKoit (Girls)', 'ABC College, Vijayawada', 'PQR College, Hyderabad', 4);
insert into results (category, event_name, winner, runner_up, sort_order) values ('sports', 'Table Tennis (Girls)', 'LMN College, Visakhapatnam', 'GHI College, Bangalore', 5);

-- ── sponsors ────────────────────────────────────────────────
delete from sponsors;

insert into sponsors (name, tier, logo, sort_order) values ('TechCorp India', 'Title Sponsor', 'TC', 0);
insert into sponsors (name, tier, logo, sort_order) values ('City Bank', 'Gold Sponsor', 'CB', 1);
insert into sponsors (name, tier, logo, sort_order) values ('Fresh Foods', 'Gold Sponsor', 'FF', 2);
insert into sponsors (name, tier, logo, sort_order) values ('Green Energy', 'Silver Sponsor', 'GE', 3);
insert into sponsors (name, tier, logo, sort_order) values ('Build Mart', 'Silver Sponsor', 'BM', 4);
insert into sponsors (name, tier, logo, sort_order) values ('CloudNet', 'Silver Sponsor', 'CN', 5);
insert into sponsors (name, tier, logo, sort_order) values ('Local FM', 'Partner', 'LF', 6);
insert into sponsors (name, tier, logo, sort_order) values ('Sports Hub', 'Partner', 'SH', 7);
insert into sponsors (name, tier, logo, sort_order) values ('Print Works', 'Partner', 'PW', 8);

-- ── gallery_images ──────────────────────────────────────────
delete from gallery_images;

insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/39722189/pexels-photo-39722189.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Traditional dance performance on colorful stage', 'large', 0);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/11211233/pexels-photo-11211233.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Basketball game action', 'medium', 1);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/1613240/pexels-photo-1613240.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Live band performance on stage', 'medium', 2);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/1396116/pexels-photo-1396116.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Fashion show model on runway', 'medium', 3);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/6896323/pexels-photo-6896323.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Theatrical drama performance', 'large', 4);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/2559741/pexels-photo-2559741.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Colorful art gallery exhibition', 'medium', 5);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/38481634/pexels-photo-38481634.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Cultural festival celebration', 'medium', 6);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/6203529/pexels-photo-6203529.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Indoor volleyball match', 'medium', 7);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/13073249/pexels-photo-13073249.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Concert with colorful stage lights', 'medium', 8);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/1526685/pexels-photo-1526685.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Abstract colorful painting', 'medium', 9);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/28587831/pexels-photo-28587831.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Fashion show with dazzling lights', 'medium', 10);
insert into gallery_images (url, alt, size, sort_order) values ('https://images.pexels.com/photos/35244385/pexels-photo-35244385.jpeg?auto=compress&cs=tinysrgb&h=650&w=940', 'Traditional dancers in vibrant costumes', 'medium', 11);

